from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class QualityMetric(models.Model):
    """Model to store quality metrics and measurements"""
    METRIC_TYPES = [
        ('defect_rate', 'Tasa de Defectos'),
        ('compliance', 'Cumplimiento'),
        ('efficiency', 'Eficiencia'),
        ('customer_satisfaction', 'Satisfacción del Cliente'),
        ('process_time', 'Tiempo de Proceso'),
    ]
    
    name = models.CharField(max_length=100, verbose_name="Nombre de Métrica")
    metric_type = models.CharField(max_length=30, choices=METRIC_TYPES, verbose_name="Tipo de Métrica")
    value = models.FloatField(verbose_name="Valor")
    target_value = models.FloatField(verbose_name="Valor Objetivo")
    unit = models.CharField(max_length=50, verbose_name="Unidad")
    date_recorded = models.DateTimeField(default=timezone.now, verbose_name="Fecha de Registro")
    recorded_by = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Registrado por")
    
    class Meta:
        verbose_name = "Métrica de Calidad"
        verbose_name_plural = "Métricas de Calidad"
        ordering = ['-date_recorded']
    
    def __str__(self):
        return f"{self.name} - {self.value}{self.unit}"

class QualityAnalysis(models.Model):
    """Model to store analysis results from the quality agent"""
    ANALYSIS_STATUS = [
        ('good', 'Bueno'),
        ('warning', 'Advertencia'),
        ('critical', 'Crítico'),
    ]
    
    title = models.CharField(max_length=200, verbose_name="Título del Análisis")
    metrics = models.ManyToManyField(QualityMetric, verbose_name="Métricas Analizadas")
    status = models.CharField(max_length=10, choices=ANALYSIS_STATUS, verbose_name="Estado")
    recommendations = models.TextField(verbose_name="Recomendaciones")
    confidence_score = models.FloatField(verbose_name="Puntuación de Confianza")
    analysis_date = models.DateTimeField(default=timezone.now, verbose_name="Fecha de Análisis")
    
    class Meta:
        verbose_name = "Análisis de Calidad"
        verbose_name_plural = "Análisis de Calidad"
        ordering = ['-analysis_date']
    
    def __str__(self):
        return f"{self.title} - {self.get_status_display()}"

class AgentAlert(models.Model):
    """Model to store alerts generated by the quality agent"""
    ALERT_TYPES = [
        ('threshold', 'Umbral Excedido'),
        ('trend', 'Tendencia Negativa'),
        ('anomaly', 'Anomalía Detectada'),
        ('compliance', 'Incumplimiento'),
    ]
    
    PRIORITY_LEVELS = [
        ('low', 'Baja'),
        ('medium', 'Media'),
        ('high', 'Alta'),
        ('urgent', 'Urgente'),
    ]
    
    alert_type = models.CharField(max_length=20, choices=ALERT_TYPES, verbose_name="Tipo de Alerta")
    priority = models.CharField(max_length=10, choices=PRIORITY_LEVELS, verbose_name="Prioridad")
    message = models.TextField(verbose_name="Mensaje")
    metric = models.ForeignKey(QualityMetric, on_delete=models.CASCADE, verbose_name="Métrica Relacionada")
    is_resolved = models.BooleanField(default=False, verbose_name="Resuelto")
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Fecha de Creación")
    resolved_at = models.DateTimeField(null=True, blank=True, verbose_name="Fecha de Resolución")
    resolved_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Resuelto por")
    
    class Meta:
        verbose_name = "Alerta del Agente"
        verbose_name_plural = "Alertas del Agente"
        ordering = ['-created_at']
    
    def __str__(self):
        return f"{self.get_alert_type_display()} - {self.get_priority_display()}"
