# Generated by Django 3.2.12 on 2025-07-12 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Métrica')),
                ('metric_type', models.CharField(choices=[('defect_rate', 'Tasa de Defectos'), ('compliance', 'Cumplimiento'), ('efficiency', 'Eficiencia'), ('customer_satisfaction', 'Satisfacción del Cliente'), ('process_time', 'Tiempo de Proceso')], max_length=30, verbose_name='Tipo de Métrica')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('target_value', models.FloatField(verbose_name='Valor Objetivo')),
                ('unit', models.CharField(max_length=50, verbose_name='Unidad')),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Métrica de Calidad',
                'verbose_name_plural': 'Métricas de Calidad',
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='QualityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Análisis')),
                ('status', models.CharField(choices=[('good', 'Bueno'), ('warning', 'Advertencia'), ('critical', 'Crítico')], max_length=10, verbose_name='Estado')),
                ('recommendations', models.TextField(verbose_name='Recomendaciones')),
                ('confidence_score', models.FloatField(verbose_name='Puntuación de Confianza')),
                ('analysis_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Análisis')),
                ('metrics', models.ManyToManyField(to='quality_agent.QualityMetric', verbose_name='Métricas Analizadas')),
            ],
            options={
                'verbose_name': 'Análisis de Calidad',
                'verbose_name_plural': 'Análisis de Calidad',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='AgentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('threshold', 'Umbral Excedido'), ('trend', 'Tendencia Negativa'), ('anomaly', 'Anomalía Detectada'), ('compliance', 'Incumplimiento')], max_length=20, verbose_name='Tipo de Alerta')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], max_length=10, verbose_name='Prioridad')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resuelto')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality_agent.qualitymetric', verbose_name='Métrica Relacionada')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por')),
            ],
            options={
                'verbose_name': 'Alerta del Agente',
                'verbose_name_plural': 'Alertas del Agente',
                'ordering': ['-created_at'],
            },
        ),
    ]
